package com.example.languagelearning// SpanishWordLearnActivity.kt
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class SpanishWordLearnActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_spanish_word_learn)
        supportActionBar?.title = "Spanish from English"

        val words = arrayListOf(
            Word("Hello", "Hola"),
            Word("Goodbye", "Adiós"),
            Word("Thank you", "Gracias"),
            Word("Please", "Por favor"),
            Word("Sorry", "Lo siento"),
            Word("Yes", "Sí"),
            Word("No", "No"),
            Word("Excuse me", "Disculpe"),
            Word("I", "Yo"),
            Word("You", "Tú"),
            Word("He", "Él"),
            Word("She", "Ella"),
            Word("We", "Nosotros"),
            Word("They", "Ellos"),
            Word("This", "Este"),
            Word("That", "Eso"),
            Word("Here", "Aquí"),
            Word("There", "Allí"),
            Word("Who", "Quién"),
            Word("What", "Qué"),
            Word("Where", "Dónde"),
            Word("When", "Cuándo"),
            Word("Why", "Por qué"),
            Word("How", "Cómo"),
            Word("Very", "Muy"),
            Word("Too", "Demasiado"),
            Word("Much", "Mucho"),
            Word("Little", "Poco"),
            Word("Big", "Grande"),
            Word("Small", "Pequeño"),
            Word("Good", "Bueno"),
            Word("Bad", "Malo"),
            Word("Right", "Derecho"),
            Word("Wrong", "Incorrecto"),
            Word("Hot", "Caliente"),
            Word("Cold", "Frío"),
            Word("New", "Nuevo"),
            Word("Old", "Viejo"),
            Word("High", "Alto"),
            Word("Low", "Bajo"),
            Word("Happy", "Feliz"),
            Word("Sad", "Triste"),
            Word("Beautiful", "Hermoso"),
            Word("Ugly", "Feo"),
            Word("Rich", "Rico"),
            Word("Poor", "Pobre"),
            Word("Easy", "Fácil"),
            Word("Difficult", "Difícil"),
            Word("Fast", "Rápido"),
            Word("Slow", "Lento"),
            Word("Near", "Cerca"),
            Word("Far", "Lejos"),
            Word("Open", "Abierto"),
            Word("Closed", "Cerrado"),
            Word("Clean", "Limpio"),
            Word("Dirty", "Sucio"),
            Word("Healthy", "Saludable"),
            Word("Sick", "Enfermo"),
            Word("Strong", "Fuerte"),
            Word("Weak", "Débil"),
            Word("Sweet", "Dulce"),
            Word("Sour", "Agujero"),
            Word("Bitter", "Amargo"),
            Word("Tasty", "Sabroso"),
            Word("Delicious", "Delicioso"),
            Word("Fresh", "Fresco"),
            Word("Rotten", "Podrido"),
            Word("Bright", "Brillante"),
            Word("Dark", "Oscuro"),
            Word("Easy", "Fácil"),
            Word("Hard", "Duro"),
            Word("Right", "Derecho"),
            Word("Left", "Izquierda"),
            Word("Front", "Frente"),
            Word("Back", "Espalda"),
            Word("Top", "Parte superior"),
            Word("Bottom", "Fondo"),
            Word("Inside", "Dentro"),
            Word("Outside", "Exterior"),
            Word("First", "Primero"),
            Word("Last", "Último"),
            Word("Next", "Próximo"),
            Word("Previous", "Anterior"),
            Word("Good morning", "Buenos días"),
            Word("Good afternoon", "Buenas tardes"),
            Word("Good evening", "Buenas noches"),
            Word("See you later", "Hasta luego"),
            Word("See you tomorrow", "Hasta mañana"),
            Word("Happy birthday", "Feliz cumpleaños"),
            Word("Merry Christmas", "Feliz Navidad"),
            Word("Happy New Year", "Feliz Año Nuevo"),
            Word("Congratulations", "Felicidades"),
            Word("Welcome", "Bienvenido"),
            Word("Good luck", "Buena suerte"),
            Word("Cheers", "Salud"),
            Word("Bon appétit", "Buen provecho"),
            Word("I love you", "Te amo"),
            Word("I miss you", "Te extraño"),
            Word("I'm sorry", "Lo siento"),
            Word("Excuse me", "Perdón"),
            Word("Help", "Ayuda"),
            Word("Fire", "Fuego"),
            Word("Police", "Policía"),
            Word("Doctor", "Doctor"),
            Word("Hospital", "Hospital"),
            Word("Money", "Dinero"),
            Word("Food", "Comida"),
            Word("Water", "Agua"),
            Word("Air", "Aire"),
            Word("Sun", "Sol"),
            Word("Moon", "Luna"),
            Word("Earth", "Tierra"),
            Word("Sky", "Cielo"),
            Word("Cloud", "Nube"),
            Word("Rain", "Lluvia"),
            Word("Snow", "Nieve"),
            Word("Wind", "Viento"),
            Word("Storm", "Tormenta"),
            Word("Thunder", "Trueno"),
            Word("Lightning", "Relámpago"),
            Word("Fire", "Fuego"),
            Word("Mountain", "Montaña"),
            Word("Tree", "Árbol"),
            Word("Flower", "Flor"),
            Word("Grass", "Hierba"),
            Word("Sea", "Mar"),
            Word("River", "Río"),
            Word("Lake", "Lago"),
            Word("Beach", "Playa"),
            Word("Desert", "Desierto"),
            Word("Forest", "Bosque"),
            Word("Jungle", "Selva"),
            Word("Bridge", "Puente"),
            Word("Road", "Carretera"),
            Word("Street", "Calle"),
            Word("House", "Casa"),
            Word("Building", "Edificio"),
            Word("Room", "Habitación"),
            Word("Bed", "Cama"),
            Word("Chair", "Silla"),
            Word("Table", "Mesa"),
            Word("Kitchen", "Cocina"),
            Word("Bathroom", "Baño"),
            Word("Toilet", "Inodoro"),
            Word("Window", "Ventana"),
            Word("Door", "Puerta"),
            Word("Key", "Llave"),
            Word("Lock", "Cerradura"),
            Word("Clock", "Reloj"),
            Word("Mirror", "Espejo"),
            Word("Picture", "Cuadro"),
            Word("TV", "Televisor"),
            Word("Computer", "Computadora"),
            Word("Phone", "Teléfono"),
            Word("Camera", "Cámara"),
            Word("Music", "Música"),
            Word("Movie", "Película"),
            Word("Book", "Libro"),
            Word("Newspaper", "Periódico"),
            Word("Magazine", "Revista"),
            Word("Map", "Mapa"),
            Word("Letter", "Carta"),
            Word("Postcard", "Postal"),
            Word("Stamp", "Sello"),
            Word("Envelope", "Sobre"),
            Word("Bag", "Bolsa"),
            Word("Shoe", "Zapato"),
            Word("Hat", "Sombrero"),
            Word("Glove", "Guante"),
            Word("Scarf", "Bufanda"),
            Word("Jacket", "Chaqueta"),
            Word("Coat", "Abrigo"),
            Word("Dress", "Vestido"),
            Word("Skirt", "Falda"),
            Word("Trousers", "Pantalones"),
            Word("Jeans", "Vaqueros"),
            Word("Shorts", "Pantalones cortos"),
            Word("Shirt", "Camisa"),
            Word("Blouse", "Blusa"),
            Word("Sweater", "Suéter"),
            Word("Socks", "Calcetines"),
            Word("Underwear", "Ropa interior"),
            Word("Bra", "Sostén"),
            Word("Pajamas", "Pijama"),
            Word("T-shirt", "Camiseta"),
            Word("Vest", "Chaleco"),
            Word("Belt", "Cinturón"),
            Word("Tie", "Corbata"),
            Word("Ring", "Anillo"),
            Word("Earring", "Pendiente"),
            Word("Necklace", "Collar"),
            Word("Bracelet", "Pulsera"),
            Word("Watch", "Reloj"),
            Word("Glasses", "Gafas"),
            Word("Sunglasses", "Gafas de sol"),
            Word("Umbrella", "Paraguas"),
            Word("Bag", "Bolsa"),
            Word("Backpack", "Mochila"),
            Word("Wallet", "Billetera"),
            Word("Money", "Dinero"),
            Word("Credit card", "Tarjeta de crédito"),
            Word("Ticket", "Boleto"),
            Word("Passport", "Pasaporte"),
            Word("ID card", "Documento de identidad"),
            Word("Driver's license", "Licencia de conducir"),
            Word("Boarding pass", "Tarjeta de embarque"),
            Word("Hotel", "Hotel"),
            Word("Room", "Habitación"),
            Word("Reservation", "Reserva"),
            Word("Reception", "Recepción"),
            Word("Lobby", "Vestíbulo"),
            Word("Elevator", "Ascensor"),
            Word("Stairs", "Escaleras"),
            Word("Floor", "Piso"),
            Word("Bed", "Cama"),
            Word("Sheets", "Sábanas"),
            Word("Blanket", "Manta"),
            Word("Pillow", "Almohada"),
            Word("Towel", "Toalla"),
            Word("Shampoo", "Champú"),
            Word("Soap", "Jabón"),
            Word("Toothbrush", "Cepillo de dientes"),
            Word("Toothpaste", "Pasta de dientes"),
            Word("Razor", "Navaja"),
            Word("Tissue", "Pañuelo"),
            Word("Trash can", "Basurero"),
            Word("Laundry", "Lavandería"),
            Word("Washing machine", "Lavadora"),
            Word("Dryer", "Secadora"),
            Word("Iron", "Plancha"),
            Word("Alarm clock", "Despertador"),
            Word("Calendar", "Calendario"),
            Word("Schedule", "Horario"),
            Word("Appointment", "Cita"),
            Word("Meeting", "Reunión"),
            Word("Party", "Fiesta"),
            Word("Holiday", "Vacaciones"),
            Word("Birthday", "Cumpleaños"),
            Word("Anniversary", "Aniversario"),
            Word("Wedding", "Boda"),
            Word("Funeral", "Funeral"),
            Word("Graduation", "Graduación"),
            Word("Celebration", "Celebración"),
            Word("Gift", "Regalo"),
            Word("Surprise", "Sorpresa"),
            Word("Decoration", "Decoración"),
            Word("Balloon", "Globo"),
            Word("Cake", "Pastel"),
            Word("Candle", "Vela"),
            Word("Fireworks", "Fuegos artificiales"),
            Word("Music", "Música"),
            Word("Dance", "Baile"),
            Word("Song", "Canción"),
            Word("Concert", "Concierto"),
            Word("Play", "Obra de teatro"),
            Word("Movie", "Película"),
            Word("Theater", "Teatro"),
            Word("Opera", "Ópera"),
            Word("Ballet", "Ballet"),
            Word("Exhibition", "Exposición"),
            Word("Museum", "Museo"),
            Word("Art", "Arte"),
            Word("Painting", "Pintura"),
            Word("Sculpture", "Escultura"),
            Word("Photography", "Fotografía"),
            Word("Drawing", "Dibujo"),
            Word("Craft", "Artesanía"),
            Word("Pottery", "Alfarería"),
            Word("Woodwork", "Carpintería"),
            Word("Sewing", "Costura"),
            Word("Knitting", "Tejer"),
            Word("Embroidery", "Bordado"),
            Word("Cooking", "Cocina"),
            Word("Baking", "Horneado"),
            Word("Recipe", "Receta"),
            Word("Ingredient", "Ingrediente"),
            Word("Flour", "Harina"),
            Word("Sugar", "Azúcar"),
            Word("Salt", "Sal"),
            Word("Oil", "Aceite"),
            Word("Butter", "Mantequilla"),
            Word("Milk", "Leche"),
            Word("Egg", "Huevo"),
            Word("Bread", "Pan"),
            Word("Rice", "Arroz"),
            Word("Pasta", "Pasta"),
            Word("Vegetable", "Vegetal"),
            Word("Fruit", "Fruta"),
            Word("Meat", "Carne"),
            Word("Chicken", "Pollo"),
            Word("Beef", "Carne de res"),
            Word("Pork", "Carne de cerdo"),
            Word("Fish", "Pescado"),
            Word("Shrimp", "Camarón"),
            Word("Crab", "Cangrejo"),
            Word("Lobster", "Langosta"),
            Word("Oyster", "Ostra"),
            Word("Clam", "Almeja"),
            Word("Soup", "Sopa"),
            Word("Salad", "Ensalada"),
            Word("Sandwich", "Sándwich"),
            Word("Pizza", "Pizza"),
            Word("Burger", "Hamburguesa"),
            Word("Fries", "Papas fritas"),
            Word("Hot dog", "Perro caliente"),
            Word("Taco", "Taco"),
            Word("Burrito", "Burrito"),
            Word("Sushi", "Sushi"),
            Word("Noodle", "Fideo"),
            Word("Ramen", "Ramen"),
            Word("Curry", "Curry"),
            Word("Stew", "Estofado"),
            Word("Grill", "Parrilla"),
            Word("BBQ", "Barbacoa"),
            Word("Fondue", "Fondue"),
            Word("Dessert", "Postre"),
            Word("Ice cream", "Helado"),
            Word("Cake", "Pastel"),
            Word("Cookie", "Galleta"),
            Word("Chocolate", "Chocolate"),
            Word("Candy", "Caramelo"),
            Word("Pie", "Pastel"),
            Word("Pudding", "Pudín"),
            Word("Custard", "Natillas"),
            Word("Jelly", "Gelatina"),
            Word("Fruit", "Fruta"),
            Word("Apple", "Manzana"),
            Word("Orange", "Naranja"),
            Word("Banana", "Plátano"),
            Word("Grape", "Uva"),
            Word("Pineapple", "Piña"),
            Word("Strawberry", "Fresa"),
            Word("Cherry", "Cereza"),
            Word("Peach", "Melocotón"),
            Word("Pear", "Pera"),
            Word("Watermelon", "Sandía"),
            Word("Mango", "Mango"),
            Word("Coconut", "Coco"),
            Word("Kiwi", "Kiwi"),
            Word("Avocado", "Aguacate"),
            Word("Papaya", "Papaya"),
            Word("Lemon", "Limón"),
            Word("Lime", "Limón"),
            Word("Grapefruit", "Toronja"),
            Word("Blueberry", "Arándano"),
            Word("Raspberry", "Frambuesa"),
            Word("Blackberry", "Mora"),
            Word("Cranberry", "Arándano rojo"),
            Word("Gooseberry", "Grosella"),
            Word("Apricot", "Albaricoque"),
            Word("Fig", "Higo"),
            Word("Date", "Dátil"),
            Word("Pomegranate", "Granada"),
            Word("Passion fruit", "Fruta de la pasión"),
            Word("Lychee", "Lichi"),
            Word("Guava", "Guayaba"),
            Word("Melon", "Melón"),
            Word("Persimmon", "Caqui"),
            Word("Plum", "Ciruela"),
            Word("Vegetable", "Vegetal"),
            Word("Potato", "Patata"),
            Word("Carrot", "Zanahoria"),
            Word("Onion", "Cebolla"),
            Word("Garlic", "Ajo"),
            Word("Tomato", "Tomate"),
            Word("Cucumber", "Pepino"),
            Word("Lettuce", "Lechuga"),
            Word("Spinach", "Espinaca"),
            Word("Broccoli", "Brócoli"),
            Word("Cabbage", "Repollo"),
            Word("Pepper", "Pimiento"),
            Word("Eggplant", "Berenjena"),
            Word("Zucchini", "Calabacín"),
            Word("Mushroom", "Seta"),
            Word("Bean", "Frijol"),
            Word("Pea", "Guisante"),
            Word("Corn", "Maíz"),
            Word("Asparagus", "Espárrago"),
            Word("Celery", "Apio"),
            Word("Radish", "Rábano"),
            Word("Beet", "Remolacha"),
            Word("Turnip", "Nabo"),
            Word("Pumpkin", "Calabaza"),
            Word("Squash", "Calabacín"),
            Word("Artichoke", "Alcachofa"),
            Word("Chili", "Chile"),
            Word("Soybean", "Soja"),
            Word("Tofu", "Tofu"),
            Word("Seaweed", "Alga marina"),
            Word("Nuts", "Nueces"),
            Word("Almond", "Almendra"),
            Word("Peanut", "Maní"),
            Word("Cashew", "Anacardo"),
            Word("Walnut", "Nuez"),
            Word("Hazelnut", "Avellana"),
            Word("Pistachio", "Pistacho"),
            Word("Coconut", "Coco"),
            Word("Macadamia", "Nuez de macadamia"),
            Word("Chestnut", "Castaña"),
            Word("Pine nut", "Piñón"),
            Word("Seed", "Semilla"),
            Word("Rice", "Arroz"),
            Word("Wheat", "Trigo"),
            Word("Barley", "Cebada"),
            Word("Oat", "Avena"),
            Word("Corn", "Maíz"),
            Word("Millet", "Mijo"),
            Word("Quinoa", "Quinua"),
            Word("Buckwheat", "Trigo sarraceno"),
            Word("Rye", "Centeno"),
            Word("Sorghum", "Sorgo"),
            Word("Spelt", "Espelta"),
            Word("Triticale", "Triticale"),
            Word("Amaranth", "Amaranto"),
            Word("Flaxseed", "Semilla de lino"),
            Word("Sunflower seed", "Semilla de girasol"),
            Word("Pumpkin seed", "Semilla de calabaza"),
            Word("Poppy seed", "Semilla de amapola"),
            Word("Sesame seed", "Semilla de sésamo"),
            Word("Hemp seed", "Semilla de cáñamo"),
            Word("Chia seed", "Semilla de chía"),
            Word("Vegetable oil", "Aceite vegetal"),
            Word("Olive oil", "Aceite de oliva"),
            Word("Coconut oil", "Aceite de coco"),
            Word("Peanut oil", "Aceite de cacahuete"),
            Word("Canola oil", "Aceite de canola"),
            Word("Sunflower oil", "Aceite de girasol"),
            Word("Soybean oil", "Aceite de soja"),
            Word("Corn oil", "Aceite de maíz"),
            Word("Sesame oil", "Aceite de sésamo"),
            Word("Flaxseed oil", "Aceite de linaza"),
            Word("Rapeseed oil", "Aceite de colza"),
            Word("Avocado oil", "Aceite de aguacate"),
            Word("Walnut oil", "Aceite de nuez"),
            Word("Grapeseed oil", "Aceite de semilla de uva"),
            Word("Almond oil", "Aceite de almendra"),
            Word("Hazelnut oil", "Aceite de avellana"),
            Word("Macadamia oil", "Aceite de nuez de macadamia"),
            Word("Palm oil", "Aceite de palma"),
            Word("Animal fat", "Grasa animal"),
            Word("Butter", "Mantequilla"),
            Word("Lard", "Manteca"),
            Word("Tallow", "Sebo"),
            Word("Duck fat", "Grasa de pato"),
            Word("Goose fat", "Grasa de ganso"),
            Word("Beef tallow", "Sebo de res"),
            Word("Pork fat", "Grasa de cerdo"),
            Word("Chicken fat", "Grasa de pollo"),
            Word("Fish oil", "Aceite de pescado"),
            Word("Cod liver oil", "Aceite de hígado de bacalao"),
            Word("Krill oil", "Aceite de krill"),
            Word("MCT oil", "Aceite de TCM"),
            Word("Emu oil", "Aceite de emú"),
            Word("Tallow", "Sebo"),
            Word("Ghee", "Ghee"),
            Word("Schmaltz", "Schmaltz"),
            Word("Bone marrow", "Médula ósea"),
            Word("Coconut milk", "Leche de coco"),
            Word("Almond milk", "Leche de almendra"),
            Word("Soy milk", "Leche de soja"),
            Word("Oat milk", "Leche de avena"),
            Word("Rice milk", "Leche de arroz"),
            Word("Hemp milk", "Leche de cáñamo"),
            Word("Cashew milk", "Leche de anacardo"),
            Word("Macadamia milk", "Leche de nuez de macadamia"),
            Word("Tiger nut milk", "Leche de chufa"),
            Word("Flax milk", "Leche de linaza"),
            Word("Sunflower milk", "Leche de girasol"),
            Word("Pumpkin seed milk", "Leche de semilla de calabaza"),
            Word("Sesame milk", "Leche de sésamo"),
            Word("Chia milk", "Leche de chía"),
            Word("Quinoa milk", "Leche de quinua"),
            Word("Potato milk", "Leche de papa"),
            Word("Barley milk", "Leche de cebada"),
            Word("Wheat milk", "Leche de trigo"),
            Word("Hazelnut milk", "Leche de avellana"),
            Word("Pecan milk", "Leche de nuez pecana"),
            Word("Brazil nut milk", "Leche de nuez de Brasil"),
            Word("Pistachio milk", "Leche de pistacho"),
            Word("Walnut milk", "Leche de nuez"),
            Word("Cottonseed milk", "Leche de semilla de algodón"),
            Word("Coconut cream", "Crema de coco"),
            Word("Almond cream", "Crema de almendra"),
            Word("Soy cream", "Crema de soja"),
            Word("Oat cream", "Crema de avena"),
            Word("Rice cream", "Crema de arroz"),
            Word("Hemp cream", "Crema de cáñamo"),
            Word("Cashew cream", "Crema de anacardo"),
            Word("Macadamia cream", "Crema de nuez de macadamia"),
            Word("Tiger nut cream", "Crema de chufa"),
            Word("Flax cream", "Crema de linaza"),
            Word("Sunflower cream", "Crema de girasol"),
            Word("Pumpkin seed cream", "Crema de semilla de calabaza"),
            Word("Sesame cream", "Crema de sésamo"),
            Word("Chia cream", "Crema de chía"),
            Word("Quinoa cream", "Crema de quinua"),
            Word("Potato cream", "Crema de papa"),
            Word("Barley cream", "Crema de cebada"),
            Word("Wheat cream", "Crema de trigo"),
            Word("Hazelnut cream", "Crema de avellana"),
            Word("Pecan cream", "Crema de nuez pecana"),
            Word("Brazil nut cream", "Crema de nuez de Brasil"),
            Word("Pistachio cream", "Crema de pistacho"),
            Word("Walnut cream", "Crema de nuez"),
            Word("Cottonseed cream", "Crema de semilla de algodón")
        )

        val recyclerView = findViewById<RecyclerView>(R.id.wordRecyclerView)
        val adapter = WordAdapter(this, words)
        recyclerView.adapter = adapter
        recyclerView.layoutManager = LinearLayoutManager(this)
    }
}
